name: blur
version: 0.1.7.6.1
summary: "Blur Network: The private cryptocurrency (https://blur.cash)"
description: |
    BLUR is a private & untraceable cryptocurrency based on the cryptonote protocol.
    The Blur Network consists of individuals mining independently on CPUs, without
    the need for specialized hardware. Join the Fight for Financial Freedom.  
grade: devel
confinement: strict

apps:
    blurd:
        daemon: forking
        command: |
          blurd-wrapper --detach --data-dir ${SNAP_COMMON} --config-file ${SNAP_USER_DATA}/etc/blurd.conf
        plugs:
            - network
            - network-bind
    blur-wallet-rpc:
        command: |
          blur-wallet-rpc --log-file ${SNAP_USER_DATA}
        plugs:
            - home
            - network
            - network-bind
    blur-wallet-cli:
        command: |
          blur-wallet-cli --log-file ${SNAP_USER_DATA}
        plugs:
            - home
            - network

parts:
    cmake-build:
        plugin: cmake
        configflags:
            - -DCMAKE_INSTALL_PREFIX=$HOME/blur
            - -DCMAKE_BUILD_TYPE=release
            - -DBUILD_TESTS=OFF
        source: .
        build-packages:
            - gcc
            - pkg-config
            - libunbound-dev
            - libevent-dev
            - libboost-all-dev
            - libssl-dev
            - libzmq3-dev
            - libpgm-dev
            - libsodium-dev
        stage-packages:
            - libminiupnpc10
            - libunbound2
            - libunwind8
        prime:
            - bin
            - usr/lib/
            - -usr/lib/gcc
            - -usr/share

    dist-files:
        plugin: dump
        source: .
        organize:
            contrib/snap/blurd.conf: etc/blurd.conf
            contrib/snap/blurd-wrapper: bin/blurd-wrapper
        prime:
            - etc
            - bin
