name: blur
version: 0.1.8.1
summary: "Blur Network: The private cryptocurrency (https://blur.cash)"
description: |
    BLUR is a private & untraceable cryptocurrency based on the cryptonote protocol.
    The Blur Network consists of individuals mining independently on CPUs, without
    the need for specialized hardware. Join the Fight for Financial Freedom.  
grade: devel
confinement: strict

apps:
    blurd:
        daemon: forking
        command: |
          blurd-wrapper --detach --data-dir ${SNAP_COMMON} --config-file ${SNAP_USER_DATA}/etc/blurd.conf
        plugs:
            - network
            - network-bind
    blur-wallet-rpc:
        command: |
          blur-wallet-rpc --log-file ${SNAP_USER_DATA}
        plugs:
            - home
            - network
            - network-bind
    blur-wallet-cli:
        command: |
          blur-wallet-cli --log-file ${SNAP_USER_DATA}
        plugs:
            - home
            - network

        build-packages:
            - gcc
            - pkg-config
            - libunbound-dev
            - libevent-dev
            - libboost-all-dev
            - libzmqpp-dev
            - libzmq3-dev
            - libsodium-dev
            - libunwind-dev
            - libminiupnpc-dev
            - libldns-dev
            - libexpat1-dev
            - libreadline6-dev
            - bison
            - doxygen
            - graphviz
        stage-packages:
            - libminiupnpc10
            - libunbound2
            - libunwind8

    dist-files:
        plugin: dump
        source: .
        organize:
            contrib/snap/blurd.conf: etc/blurd.conf
            contrib/snap/blurd-wrapper: bin/blurd-wrapper
        prime:
            - etc
            - bin

